version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=development

networks:
  default:
    external:
      name: default
