version: "3"
name: fruitify-dev
services:

  nginx:
    container_name: nginx
    hostname: nginx
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: dev.dockerfile
      context: ./nginx
    ports:
      - "80:80"
    links:
      - api
      - client

  client:
    container_name: client
    hostname: client
    build:
      dockerfile: dev.dockerfile
      context: ./client
    command: /bin/sh -c "while sleep 1000; do :; done"
    depends_on:
      - api
    volumes:
      - ./client:/workspaces/client
    stdin_open: true
    tty: true

  api:
    container_name: api
    hostname: api
    restart: always
    build:
      dockerfile: dev.dockerfile
      context: ./api
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ./api:/workspaces/api
