version: "3"
name: "fruitify"
services:

  nginx:
    depends_on:
      - api
      - client
    restart: always
    image: mancarius/fruitify:nginx-1.0.0
    volumes:
      - client-dist:/usr/share/nginx/html
    ports:
      - "80:80"
    links:
      - api
      - client

  client:
    image: mancarius/fruitify:client-1.0.0
    depends_on:
      - api
    volumes:
      - client-dist:/client/dist
    stdin_open: true
    tty: true

  api:
    restart: always
    image: mancarius/fruitify:api-1.0.0
    command: npm run start
    volumes:
      - type: bind
        source: ./api
        target: /api
      - /api/node_modules

volumes:
  client-dist:
