version: "3"
name: "fruitify-prod"
services:

  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: prod.dockerfile
      context: ./nginx
    volumes:
      - client-dist:/usr/share/nginx/html
    ports:
      - "80:80"
    links:
      - api
      - client

  client:
    build:
      dockerfile: prod.dockerfile
      context: ./client
    depends_on:
      - api
    volumes:
      - client-dist:/client/dist
    stdin_open: true
    tty: true

  api:
    restart: always
    build:
      dockerfile: prod.dockerfile
      context: ./api
    command: npm run start
    volumes:
      - type: bind
        source: ./api
        target: /api
      - /api/node_modules

volumes:
  client-dist:
