import { Fruit } from 'src/fruits/models/fruit.model';

export default <Fruit[]>[
  {
    id: 1,
    genus: 'Malus',
    name: 'Apple',
    family: 'Rosaceae',
    order: 'Rosales',
    nutritions: {
      carbohydrates: 13.81,
      protein: 0.26,
      fat: 0.17,
      calories: 52,
      sugar: 10.39,
    },
  },
  {
    id: 2,
    genus: 'Citrus',
    name: 'Orange',
    family: 'Rutaceae',
    order: 'Sapindales',
    nutritions: {
      carbohydrates: 8.3,
      protein: 1.2,
      fat: 0.2,
      calories: 43,
      sugar: 8.2,
    },
  },
  {
    id: 3,
    genus: 'Musa',
    name: 'Banana',
    family: 'Musaceae',
    order: 'Zingiberales',
    nutritions: {
      carbohydrates: 22.84,
      protein: 1.09,
      fat: 0.33,
      calories: 89,
      sugar: 12.23,
    },
  },
  {
    id: 4,
    genus: 'Prunus',
    name: 'Cherry',
    family: 'Rosaceae',
    order: 'Rosales',
    nutritions: {
      carbohydrates: 12.18,
      protein: 1.06,
      fat: 0.2,
      calories: 50,
      sugar: 8.49,
    },
  },
  {
    id: 5,
    genus: 'Vitis',
    name: 'Grape',
    family: 'Vitaceae',
    order: 'Vitales',
    nutritions: {
      carbohydrates: 18.1,
      protein: 0.72,
      fat: 0.16,
      calories: 69,
      sugar: 15.48,
    },
  },
  {
    id: 6,
    genus: 'Fragaria',
    name: 'Strawberry',
    family: 'Rosaceae',
    order: 'Rosales',
    nutritions: {
      carbohydrates: 7.68,
      protein: 0.67,
      fat: 0.3,
      calories: 32,
      sugar: 4.89,
    },
  },
  {
    id: 7,
    genus: 'Actinidia',
    name: 'Kiwi',
    family: 'Actinidiaceae',
    order: 'Theales',
    nutritions: {
      carbohydrates: 14.66,
      protein: 1.14,
      fat: 0.52,
      calories: 61,
      sugar: 9.0,
    },
  },
  {
    id: 8,
    genus: 'Ananas',
    name: 'Pineapple',
    family: 'Bromeliaceae',
    order: 'Poales',
    nutritions: {
      carbohydrates: 13.12,
      protein: 0.54,
      fat: 0.12,
      calories: 50,
      sugar: 9.85,
    },
  },
  {
    id: 9,
    genus: 'Citrullus',
    name: 'Watermelon',
    family: 'Cucurbitaceae',
    order: 'Cucurbitales',
    nutritions: {
      carbohydrates: 8.1,
      protein: 0.61,
      fat: 0.15,
      calories: 30,
      sugar: 6.2,
    },
  },
  {
    id: 10,
    genus: 'Cocos',
    name: 'Coconut',
    family: 'Arecaceae',
    order: 'Arecales',
    nutritions: {
      carbohydrates: 15.23,
      protein: 2.0,
      fat: 33.49,
      calories: 354,
      sugar: 6.23,
    },
  },
  {
    id: 11,
    genus: 'Mangifera',
    name: 'Mango',
    family: 'Anacardiaceae',
    order: 'Sapindales',
    nutritions: {
      carbohydrates: 14.98,
      protein: 0.82,
      fat: 0.38,
      calories: 60,
      sugar: 14.8,
    },
  },
  {
    id: 12,
    genus: 'Rubus',
    name: 'Raspberry',
    family: 'Rosaceae',
    order: 'Rosales',
    nutritions: {
      carbohydrates: 5.44,
      protein: 1.2,
      fat: 0.65,
      calories: 52,
      sugar: 4.42,
    },
  },
  {
    id: 13,
    genus: 'Ficus',
    name: 'Fig',
    family: 'Moraceae',
    order: 'Rosales',
    nutritions: {
      carbohydrates: 19.18,
      protein: 0.75,
      fat: 0.3,
      calories: 74,
      sugar: 16.26,
    },
  },
  {
    id: 14,
    genus: 'Pyrus',
    name: 'Pear',
    family: 'Rosaceae',
    order: 'Rosales',
    nutritions: {
      carbohydrates: 15.23,
      protein: 0.38,
      fat: 0.12,
      calories: 57,
      sugar: 9.8,
    },
  },
  {
    id: 15,
    genus: 'Vaccinium',
    name: 'Blueberry',
    family: 'Ericaceae',
    order: 'Ericales',
    nutritions: {
      carbohydrates: 14.49,
      protein: 0.74,
      fat: 0.33,
      calories: 57,
      sugar: 9.96,
    },
  },
  {
    id: 16,
    genus: 'Prunus',
    name: 'Plum',
    family: 'Rosaceae',
    order: 'Rosales',
    nutritions: {
      carbohydrates: 9.92,
      protein: 0.7,
      fat: 0.28,
      calories: 46,
      sugar: 8.4,
    },
  },
  {
    id: 17,
    genus: 'Prunus',
    name: 'Apricot',
    family: 'Rosaceae',
    order: 'Rosales',
    nutritions: {
      carbohydrates: 11.12,
      protein: 0.49,
      fat: 0.39,
      calories: 48,
      sugar: 9.24,
    },
  },
  {
    id: 18,
    genus: 'Cucumis',
    name: 'Cucumber',
    family: 'Cucurbitaceae',
    order: 'Cucurbitales',
    nutritions: {
      carbohydrates: 3.63,
      protein: 0.65,
      fat: 0.11,
      calories: 16,
      sugar: 1.67,
    },
  },
  {
    id: 19,
    genus: 'Cucumis',
    name: 'Melon',
    family: 'Cucurbitaceae',
    order: 'Cucurbitales',
    nutritions: {
      carbohydrates: 8.16,
      protein: 0.84,
      fat: 0.19,
      calories: 34,
      sugar: 7.86,
    },
  },
  {
    id: 20,
    genus: 'Citrus',
    name: 'Lemon',
    family: 'Rutaceae',
    order: 'Sapindales',
    nutritions: {
      carbohydrates: 9.32,
      protein: 1.1,
      fat: 0.3,
      calories: 29,
      sugar: 2.5,
    },
  },
  {
    id: 21,
    genus: 'Citrus',
    name: 'Lime',
    family: 'Rutaceae',
    order: 'Sapindales',
    nutritions: {
      carbohydrates: 10.54,
      protein: 0.7,
      fat: 0.2,
      calories: 30,
      sugar: 1.7,
    },
  },
  {
    id: 22,
    genus: 'Citrus',
    name: 'Grapefruit',
    family: 'Rutaceae',
    order: 'Sapindales',
    nutritions: {
      carbohydrates: 8.08,
      protein: 0.77,
      fat: 0.1,
      calories: 32,
      sugar: 7.0,
    },
  },
  {
    id: 23,
    genus: 'Citrus',
    name: 'Tangerine',
    family: 'Rutaceae',
    order: 'Sapindales',
    nutritions: {
      carbohydrates: 13.34,
      protein: 0.81,
      fat: 0.31,
      calories: 53,
      sugar: 10.58,
    },
  },
  {
    id: 24,
    genus: 'Cucumis',
    name: 'Honeydew',
    family: 'Cucurbitaceae',
    order: 'Cucurbitales',
    nutritions: {
      carbohydrates: 9.09,
      protein: 0.54,
      fat: 0.14,
      calories: 36,
      sugar: 8.12,
    },
  },
  {
    id: 25,
    genus: 'Cucumis',
    name: 'Cantaloupe',
    family: 'Cucurbitaceae',
    order: 'Cucurbitales',
    nutritions: {
      carbohydrates: 8.16,
      protein: 0.84,
      fat: 0.19,
      calories: 34,
      sugar: 7.86,
    },
  },
  {
    id: 26,
    genus: 'Citrus',
    name: 'Pomelo',
    family: 'Rutaceae',
    order: 'Sapindales',
    nutritions: {
      carbohydrates: 9.62,
      protein: 0.76,
      fat: 0.04,
      calories: 38,
      sugar: 6.1,
    },
  },
  {
    id: 27,
    genus: 'Citrus',
    name: 'Mandarin',
    family: 'Rutaceae',
    order: 'Sapindales',
    nutritions: {
      carbohydrates: 11.54,
      protein: 0.81,
      fat: 0.31,
      calories: 53,
      sugar: 10.58,
    },
  },
  {
    id: 28,
    genus: 'Citrus',
    name: 'Kumquat',
    family: 'Rutaceae',
    order: 'Sapindales',
    nutritions: {
      carbohydrates: 15.9,
      protein: 1.88,
      fat: 0.86,
      calories: 71,
      sugar: 9.36,
    },
  },
  {
    id: 29,
    genus: 'Citrus',
    name: 'Ugli fruit',
    family: 'Rutaceae',
    order: 'Sapindales',
    nutritions: {
      carbohydrates: 9.62,
      protein: 0.76,
      fat: 0.04,
      calories: 38,
      sugar: 6.1,
    },
  },
  {
    id: 30,
    genus: 'Citrus',
    name: 'Bergamot',
    family: 'Rutaceae',
    order: 'Sapindales',
    nutritions: {
      carbohydrates: 6.2,
      protein: 0.5,
      fat: 0.2,
      calories: 25,
      sugar: 4.0,
    },
  },
  {
    id: 31,
    genus: 'Citrus',
    name: 'Yuzu',
    family: 'Rutaceae',
    order: 'Sapindales',
    nutritions: {
      carbohydrates: 9.32,
      protein: 1.1,
      fat: 0.3,
      calories: 29,
      sugar: 2.5,
    },
  },
  {
    id: 32,
    genus: 'Citrus',
    name: 'Calamondin',
    family: 'Rutaceae',
    order: 'Sapindales',
    nutritions: {
      carbohydrates: 9.32,
      protein: 1.1,
      fat: 0.3,
      calories: 29,
      sugar: 2.5,
    },
  },
  {
    id: 33,
    genus: 'Citrus',
    name: 'Sudachi',
    family: 'Rutaceae',
    order: 'Sapindales',
    nutritions: {
      carbohydrates: 9.32,
      protein: 1.1,
      fat: 0.3,
      calories: 29,
      sugar: 2.5,
    },
  },
  {
    id: 34,
    genus: 'Citrus',
    name: 'Seville orange',
    family: 'Rutaceae',
    order: 'Sapindales',
    nutritions: {
      carbohydrates: 9.32,
      protein: 1.1,
      fat: 0.3,
      calories: 29,
      sugar: 2.5,
    },
  },
  {
    id: 35,
    genus: 'Citrus',
    name: 'Finger lime',
    family: 'Rutaceae',
    order: 'Sapindales',
    nutritions: {
      carbohydrates: 9.32,
      protein: 1.1,
      fat: 0.3,
      calories: 29,
      sugar: 2.5,
    },
  },
  {
    id: 36,
    genus: 'Citrus',
    name: "Buddha's hand",
    family: 'Rutaceae',
    order: 'Sapindales',
    nutritions: {
      carbohydrates: 9.32,
      protein: 1.1,
      fat: 0.3,
      calories: 29,
      sugar: 2.5,
    },
  },
  {
    id: 37,
    genus: 'Citrus',
    name: 'Satsuma',
    family: 'Rutaceae',
    order: 'Sapindales',
    nutritions: {
      carbohydrates: 11.54,
      protein: 0.81,
      fat: 0.31,
      calories: 53,
      sugar: 10.58,
    },
  }
];
